### ISSUE TITLE
Pipo Range: How to set up distance ?

### ISSUE THREAD

**Issue by Leo-Nicolle** [rupraph/pipo-modules-FW#2]
Here is how I see the thing, let me know if I am right:

## Hands detection
[Schema](https://excalidraw.com/#json=z8TjTBSrTRci0E98g7zdb,0mZ-p0XoLXib0ptuEmVNqg)
 - When you are between `inputMin` and `inputMax` that you define in your MIDI or HID config, it interpolates
 - When you are between `limit_min` and `inputMin` you play note min
 - When you are between `limit_max` and `inputMax` you play note max
 - When you are below `limit_min` or above `limit_max`: act as if there were no one.

## Hands movement
[Schema](https://excalidraw.com/#json=Os6xab7Rhoqm--JyReE4Q,AzK8w7Nm2RtPlQAC27iH0w)
  - When you move your hand between `inputMin` and `inputMax`, you trigger `note_on`
  - When you stop your hand between `inputMin` and `inputMax`, it triggers a `note_on`  as long as you don't move
  - When you move again your hand after you stopped, it note_off the inifinite note, will it sound ok ?

**Comment by rupraph** [comment]
Let's not forget that part of this logic should be generic enough to be used with various sensors

# Hands detection
- we should indeed define an active zone for the sensor. We could have a symetrical deadzone around zero + a maximum limiter value. this should be set in the sensor class so that it can be in the sensor units. If in dead zone return 0, above max, cap value at max. 
- on this range we should spread/interpolate the selected number of notes.
- the sub range you describe with limit_min/limit_max to me is virtual in the sense that it is the role of the miditranslator to "leave some space" in the active range to match with min/max notes (this is not currently the case)
- overall you play notes, or send cc, or hid, or anything only when in the active range.  

Note: I saw currently the raw sensor value in not stored in the sensor dat. We should have if so that we can display/plot it.

# Hands movement

- when you enter the active zone, you send the corresponding note On
- when you leave the active zone you send all note offs (Note: could be a nice additional setting to choose to only off the last played note if sustain is not set to infinite) 
- when you navigate the zone, you trigger new notes On 
- a note0n is always only sent once:
-- except if the sustain time of the note is expired then the note can be retrigger
-- if another note is triggered in the meantime and it comes back, note can be retriggered before end of sustain
- in general user shall be able to choose between infinite or specific sustain time (maybe this could even go futher to improve musicality, like sustain velocity based, or whatever... for later)
- user can choose that, when triggering a new note, wherther it also shutsoff the previous one, no matter the sustain status.

Sidenote: (it could be nice for other sensors,to have the sustain duration, controled by another sensor axis. Like the pedal on a piano) 

For range, quick settings behaviours could be:
- some sustain without switching previous note off (alike a harp)
- inifite sustain and stop old note before previous

Hope this is somewhat clear :) 
The bigger rework should be in the engine I guess. 
Also I think right now one issue is the fact that all midi translators currently have a defined input min/max, which I now doubt the utility since this should just be the sensor output range to which they are associated

Bisous

**Comment by Leo-Nicolle** [comment]
I was playing with adding sound to the config page and here is what I got: 
 
## Moving hand
https://github.com/rupraph/pipo-single/assets/7451806/6b86f094-23ee-486e-9f95-9c6cfed1e229

## Immobile

https://github.com/rupraph/pipo-single/assets/7451806/2824e4dd-e5dd-41da-95d3-1f870f75dd6e



  - I allow 12 simultaneous notes
  - I shut down a note only when receiving note-off

## Actual Behaviour
 - When I don't move my hand, notes are set to off immediately, we hear the notes only because I delay the note-off for one second
 - When I move my hand it switches to the next note nicelly
 - When I remove my hand from the field of view, everything shuts down
 - When I put my hand super close to Pipo, it plays the most bass note over and over (same as immobile hand farther away)
 - When I put my hand super far, it shuts down everything.

## Expected behaviour: 
 I think that we are not too far from what we talked about, I would say: 
 - we have to fix this noteoff that comes too early when the hand does not move

## Settings
 - We don't have a dead zone close by pipo, it seems to ignore the  `input.min` distance I send him (might be config update problems)
 - The `input.max` does not seem to work either: pipo stops reacting always at the same distance, no matter what `input.max` I send him. 

I'll upload you the last changes on my branch so you can test and hear it.

**Comment by Leo-Nicolle** [comment]
Also, to have access to MIDI stuff in PIPO we will need `https`
Do you mind if I try to use [this](https://github.com/fhessel/esp32_https_server) ?

**Comment by rupraph** [comment]
Wow ! that looks nice ! :)

Unfortunately, I can't hear the sound on the video, don't know why...
But that's an extra mile, I didn't knew you were adding audio. That's a good bonus to help wquickly adjust the settings.

Anyway, don't forget this note section is only active when the sensor axis is set to "note mode". So when in CC (continuous control mode, or OSC), the keyboard will likely have to hide.
 (Also, for pipo motion who has more axis, we will have to see if one keyboard plays all notes, or if we have smaller ones for each axis).

**Comment by rupraph** [comment]
Regarding the server, I do not mind too much which one we use as long as the licencing is ok. However, I understood that we better have an "async" sever on the esp, not to block execution of the code. And I am unsure the one you found is async. 
There migh be a workaround by starting to distribute tasks between cores using freertos, but it is extra work. 

What is exactly the issue you are encountering, I am not sure what you mean by accessing midi in pipo.

**Comment by Leo-Nicolle** [comment]
There is a thing called [webMIDI](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API) which allows you to talk to MIDI devices from your browser in Javascript. But nowadays you know, browsers do not allow you to measure time accurately, or share memory between tabs or access USB devices unless you are in a *secure* environment. Not fun. So we need a secure environment if we want to connect to Pipo using webMIDI. 

There is also another workaround that I just remembered we talked about: we could do the whole communication via http and just read the internal state of PIPO. I can try that as a first step.

**Comment by Leo-Nicolle** [comment]
Yes, I'll see how I'll handle the multi dimensional ones, maybe the keyboard will have a channel selector or something. 
  - The lib I found has async server (separate thread, perfect), and it is in MIT
  - Yeah I figured I needed sound to debug and as I did not know MIDI that much I just had a quick look at how to generate sound from the browser and voila! hahaha
  - Yes I never tried the CCs yet, cause I don't really understand what it is, I need to watch a video about it. And we'll need to find a way to represent them

**Comment by rupraph** [comment]
> There is a thing called [webMIDI](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API) which allows you to talk to MIDI devices from your browser in Javascript. But nowadays you know, browsers do not allow you to measure time accurately, or share memory between tabs or access USB devices unless you are in a _secure_ environment. Not fun. So we need a secure environment if we want to connect to Pipo using webMIDI.
> 
> There is also another workaround that I just remembered we talked about: we could do the whole communication via http and just read the internal state of PIPO. I can try that as a first step.

Ok, I see, did not knew webmidi requires Https. However, where webmidi would really be usefull, is when you have a web based synth open on your pc (from somewhere else on the web), and you want to control it using a pipo. I don't think there is much added value to have it on the config page hosted by the pipo. So maybe we can indead use internal processing to pass data to the config server, and rely on the public websynths to provide a secure env ? 

I'll leave it up to you.

**Comment by rupraph** [comment]
> Yes, I'll see how I'll handle the multi dimensional ones, maybe the keyboard will have a channel selector or something.
> 
>     * The lib I found has async server (separate thread, perfect), and it is in MIT
Great ! :)
>     * Yeah I figured I needed sound to debug and as I did not know MIDI that much I just had a quick look at how to generate sound from the browser and voila! hahaha
> 
>     * Yes I never tried the CCs yet, cause I don't really understand what it is, I need to watch a video about it. And we'll need to find a way to represent them
-> CC are basically used for button controls. When you control a synth with midi, you can assign CC to your synth button, to adjust effects or other various parameters, which are not notes
